config/routes.rb
Rails.application.routes.draw do
  get 'users/new', :as => 'signup'
  get 'static_pages/help', :as => 'help'
  get 'static_pages/about', :as => 'about'
  root 'reminders#index'
  resources :reminders
  resources :users
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  validates :reminder, presence: true
  #belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  #has_many :reminders
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maxiumum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.].[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:reminder, :due)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "To Do on Rails"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=News+Cycle" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page-content">
  <h1 class="center" id="page-title"><%= link_to 'To-Do on Rails', root_path %></h1>
  <div class="center"><%= link_to 'New Reminder', new_reminder_path %></div>

  <%= yield %>

</div>

<div class="center">
  <%= link_to 'Sign-Up', signup_path %> | 
  <%= link_to 'Help', help_path %> | 
  <%= link_to 'About', about_path %>
</body>
</html>

app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reminder %><br>
    <%= f.text_area :reminder %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.datetime_select :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form' %>

<p>Lasted edited at: <%= @reminder.updated_at.strftime("%x @ %r") %></p>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<% provide(:title, "Home") %>
<p id="notice"><%= notice %></p>

<% @reminders.each do |reminder| %>
  <div class="reminder_container">
    <div class="reminder_container-top">
      <span class="due_at"><strong>Due:</strong></span> <%= reminder.due.strftime("%x @ %r") %><br>
      <span class="created_at"><strong>Created at:</strong></span> <%= reminder.created_at.strftime("%x @ %r") %>
    </div>
    <div class="reminder_container-bottom">
      <%= simple_format h reminder.reminder %>
    </div>
    <div class="reminder_container-menu">
      <%= link_to 'View', reminder %> | <%= link_to 'Edit', edit_reminder_path(reminder) %> | <%= link_to 'Done (Delete)', reminder, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="reminder_container">
  <div class="reminder_container-top">
    <span class="due_at"><strong>Due:</strong></span> <%= @reminder.due.strftime("%x @ %r") %><br>
    <span class="created_at"><strong>Created at:</strong></span> <%= @reminder.created_at.strftime("%x @ %r") %>
  </div>
  <div class="reminder_container-bottom">
    <%= simple_format h @reminder.reminder %>
  </div>
  <div class="reminder_container-menu">
    <%= link_to 'Edit', edit_reminder_path(@reminder) %> | <%= link_to 'Back', reminders_path %>
  </div>
  <div class="reminder_container-update">
    <span class="updated_at"><strong>Last updated:</strong></span> <%= @reminder.updated_at.strftime("%x @ %r") %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1 class="center">About</h1>
<p>This is a to-do list toy application written in Ruby and running on Rails. That is all you should probably need to know.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1 class="center">Help</h1>
<p>First, add a to-do reminder with a due date. When you have managed to complete said task, go ahead and delete. It's really that simple.</p>

app/views/users/new.html.erb
<% provide(:title, "New User Sign Up") %>r
<h1 class="center">New User Sign Up</h1>
<p>Doing big things here...</p>